stages:
  - build

variables:
  APP_NAME: "kbot"
  DOCKER_REPO: "ghcr.io/kylib4444/kbot_my"

build_job:
  stage: build
  image: golang:1.23
  parallel:
    matrix:
      - ARCH: ["amd64", "arm64"]
        OS: ["linux", "darwin", "windows"]
  script:
    - echo "Збірка для $OS на архітектурі $ARCH"
    - GOOS=$OS GOARCH=$ARCH go build -v -o ./bin/${APP_NAME}_${OS}_${ARCH}
    - echo "Файл зібрано успішно:./bin/${APP_NAME}_${OS}_${ARCH}"
  rules:
    - if: '$OS == "windows"'
      allow_failure: true
    - allow_failure: false
  artifacts:
    paths:
      - ./bin/