replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "kylib4444/kbot_my"
  tag: "v1.0.0-d8a0842-linux-amd64"
  os: linux
  arch: amd64
secret:
  name: kbot_my
  tokenKey: token
  tokenName: TELE_TOKEN
service:
  type: ClusterIP
  port: 80
serviceAccount:
  create: false
  name: ""
